### ISSUE TITLE
`wrap` closures

### ISSUE THREAD

**Issue by mzgubic** [invenia/TimeDag.jl#16]
At the moment, wrapping closures does not seem to be possible, i.e.

```julia
using Dates
using TimeDag

struct Foo
	a
end

let
    A = block_node(Block([DateTime(2021, 1, 3 * i) for i in 1:10], [3.0*i for i in 1:10]))
    foo = Foo(3.0)
    evaluate(wrap(node -> foo.a + node)(A), DateTime(2021, 1, 1), DateTime(2021, 1, 10))
end
```

gives
```julia
ERROR: TypeError: in Type, in parameter, expected Type, got a value of type var"#13#16"{Foo}
Stacktrace:
 [1] wrap(f::Function)
   @ TimeDag ~/JuliaEnvs/TimeDagForecasters/dev/TimeDag/src/ops/core.jl:100
 [2] top-level scope
   @ REPL[6]:4
```

(I am using `let` to create a local scope, which makes `foo` a local variable - there is no need to close over globals)

**Comment by tpgillam** [comment]
I'm just playing around with this. I don't really understand the details of how Julia implements closures, and when we might hit different cases. For example, I observe that the behaviour is good if `Foo.a` is given a more specific type, like an `Int64`.

I do see a semantic problem here though — namely, for arbitrary `a`, it could be mutable (e.g. some kind of `Vector`). In this case the node is invalid, since it depends upon external mutable state.
 
(P.S. In the closure, the argument called `node` won't be a node, but a value :) )

**Comment by mzgubic** [comment]
>I'm just playing around with this. I don't really understand the details of how Julia implements closures, and when we might hit different cases. For example, I observe that the behaviour is good if Foo.a is given a more specific type, like an Int64.

My (quite basic) understanding is that it creates a callable struct under the hood. But I don't know why using a more specific type works.

>I do see a semantic problem here though — namely, for arbitrary a, it could be mutable (e.g. some kind of Vector). In this case the node is invalid, since it depends upon external mutable state.

I see, that makes sense - will close the issue.

>(P.S. In the closure, the argument called node won't be a node, but a value :) )

Yep, thanks, idk why I called it that
